Big 199 bq handle exotic datatypes filtering
keboola/php-storage-driver-bigquery pull request #103
Opened 2023-12-20 13:05 UTC by tomasfejfar

Jira: [BIG-199](https://keboola.atlassian.net/browse/BIG-199)
Tests: https://github.com/keboola/storage-api-php-client/pull/1242
Driver:
KBC: https://github.com/keboola/connection/pull/4775

2024-01-02 09:16 UTC, zajca requested changes
Chtělo by to přidat test.

2024-01-02 09:16 UTC, zajca commented on src/Handler/Table/Preview/PreviewTableHandler.php
> +        ];
To by mohla byt konstanta klidně

2024-01-02 09:48 UTC, tomasfejfar commented on src/Handler/Table/Preview/PreviewTableHandler.php
> +        ];
Done.

2024-01-02 11:35 UTC, tomasfejfar commented on tests/functional/UseCase/Table/PreviewTableTest.php
> +        foreach ([
test tu

2024-01-03 07:15 UTC, zajca approved these changes

2024-01-03 08:03 UTC, merged