CT-1054
keboola/php-storage-driver-bigquery pull request #116
Opened 2024-02-28 19:05 UTC by zajca

Jira: BIG-XXX
Connection PR: XXX
SAPI PR: XXX

---

2024-02-29 09:54 UTC, zajca commented on src/Handler/Info/ObjectInfoHandler.php
> +                    $table->rows();
toto bych řekl že dřív na view nešlo, ale asi to už ide :D

2024-02-29 09:55 UTC, zajca commented on tests/functional/UseCase/Info/ObjectInfoErrorTest.php
> +        );
toto byl nějaký pohrobek co sa zapomněl odkomentovat

2024-02-29 09:57 UTC, zajca commented on tests/functional/UseCase/Project/CreateDropProjectTest.php
> +        );
začal padat create projekt BQ udělalo asi nějaků změnu a sů tam services navíc. Takže sem dal jen ty naše expected co je tam na víc to neřeší.

2024-02-29 15:15 UTC, tomasfejfar requested changes, later dismissed
Padají ti testy. Kód vypadá dobře. Nechceme zkusit ten partitionFilter načíst a selectnout s ním?

2024-02-29 15:15 UTC, tomasfejfar commented on src/Handler/Info/ObjectInfoHandler.php
> +        } catch (TableNotExistsReflectionException) {
Nice :) To jsem ještě nepoužil nikde

2024-02-29 15:15 UTC, tomasfejfar commented on tests/functional/UseCase/Info/ObjectInfoTest.php
> +                'View "%s:%s.partitionedView" has enabled partitionFilter we are not able to check if it\'s readable.',
```suggestion
                'The view "%s:%s.partitionedView" has a partition filter set, which stops us from verifying if it can be read.',
```

2024-02-29 15:15 UTC, tomasfejfar commented on tests/functional/UseCase/Info/ObjectInfoTest.php
> +                'View "%s:%s.partitionedView" has enabled partitionFilter we are not able to check if it\'s readable.',
https://chat.openai.com/g/g-e0mTpruTx-saas-english-fixer

2024-03-01 07:09 UTC, zajca commented
> Padají ti testy. Kód vypadá dobře. Nechceme zkusit ten partitionFilter načíst a selectnout s ním?

Test sem spravil byl tam zakomentovaný kus kódu. Partition filter z toho view nezjistíš to tam není a ve view definition je taky prd. Musel bys nějak vyparsovat původní tabulku a s ní pak zjistit jestli je tam partition.

2024-03-05 11:17 UTC, romanbracinik commented
👁️

2024-03-05 11:27 UTC, romanbracinik approved these changes
cajk, neni mi akurat jasne preco je tam zakomentovany ten assert

2024-03-05 11:27 UTC, romanbracinik commented on tests/functional/UseCase/Info/ObjectInfoTest.php
> +//        $this->assertCount(3, $logs);
preco je ten assert zakomentovany ?

2024-03-05 11:32 UTC, zajca commented on tests/functional/UseCase/Info/ObjectInfoTest.php
> +//        $this->assertCount(3, $logs);
dík toho sem si nevšiml

2024-03-05 12:23 UTC, merged