Roman add table info create table
keboola/php-storage-driver-bigquery pull request #14
Opened 2022-11-14 11:41 UTC by romanbracinik

2022-11-14 11:42 UTC, romanbracinik commented on src/Handler/Table/Create/CreateTableHandler.php
> -        assert($command->getPrimaryKeysNames()->count() === 0, 'CreateTableCommand.primaryKeysNames is not supported in Bigquery');
odoborem len assert dalej sa nastavuje [] pretoze to BQ nepodporuje ale nemalo byt o spadnut aby to bolo co najvac podobne ostatnym implementaciam

2022-11-15 13:33 UTC, zajca approved these changes

2022-11-15 14:01 UTC, martinjunger requested changes
Mela by se vracet `ObjectInfoResponse`, nikoliv jen `TableInfo`, viz komentare...

2022-11-15 14:01 UTC, martinjunger commented on src/Handler/Table/Create/CreateTableHandler.php
> +        return TableReflectionResponseTransformer::transformTableReflectionToResponse($datasetName, $ref);
Pridam to jeste sem:
> podle me by to melo vracet spis ObjectInfoResponse + ObjectType::TABLE, jako je to v `ObjectInfoHandler`...
> viz https://github.com/keboola/php-storage-driver-teradata/pull/42#discussion_r1022808057

2022-11-16 11:17 UTC, martinjunger approved these changes
👍

2022-11-16 15:13 UTC, romanbracinik commented
formalne davam este na jedno review po rebase som tam riesil konflikt a pridal jeden commit 17910033500b7aeb6f57d7ca6b5da2feb003c749

2022-11-18 09:40 UTC, zajca approved these changes

2022-11-18 10:45 UTC, merged