CT-1842 use CREATE TABLE COPY when creating stage table
keboola/php-storage-driver-bigquery pull request #154
Opened 2024-12-17 09:35 UTC by zajca

Jira: CT-1842
Connection PR: XXX
SAPI PR: XXX

---

2024-12-18 11:31 UTC, zajca commented on src/Handler/Table/Import/ImportTableFromTableLib/CopyImportFromTableToTable.php
> +class CopyImportFromTableToTable implements ToStageImporterInterface
Místo přidávání adapteru sem to naimplementoval takto celé, stejně to chceme přesůvat mimo IE lib takže to dává tak nějak smysl.

2024-12-18 11:31 UTC, zajca commented on tests/functional/UseCase/Table/Import/FromTable/ImportTableFromTableTest.php
> +            ));
assert je upravený nevěděl sem proč mě padá test a padal protože sem potřeboval rozšířit try/catch kde to háže exception

2024-12-18 11:32 UTC, zajca commented on tests/functional/UseCase/Workspace/ResetWorkspacePasswordTest.php
> +            $this->assertSame(401, $e->getCode());
ten assert byl na prd

2024-12-18 11:34 UTC, zajca commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +        }
prakticky pokud ty sloupce nepotřebujů rename tak to ide přes copy. Přemýšlal sem o tom, že bych bych ty sloupce aj přejmenovával po copy, ale to mě přišlo jako overkill, on stejně IM pro BQ není takže ten rename sloupců tam byt teď nemože.
Stejně tak aj pokud by sa měnil typ u netypových tabulek tak by to nefakčilo, ale to taky teď nejde.

2025-01-17 09:25 UTC, zajca commented on src/Client/BigQuery/Retry.php
> -            if (in_array($statusCode, [429, 500, 503,])) {
To je problém proč padaly testy :) 401 sa nedělal retry, problém je, že teď sa dělá takže když dojdů vadné credentials tak sa to bude pár minut točit, bude potřeba to ošetřit v connection a v sapi testech jinak to bude zdržovat.

2025-01-17 09:45 UTC, zajca commented on tests/functional/UseCase/Workspace/ResetWorkspacePasswordTest.php
> +            1,
tady sem změnul retry na 1

2025-01-17 13:04 UTC, vojtabiberle commented
PLS doplň nějaké "changes" v description.

2025-01-17 13:08 UTC, zajca commented
> PLS doplň nějaké "changes" v description.

Přidáno

2025-01-17 13:24 UTC, vojtabiberle requested changes
Za mě hlavně doplnit changes do description prosím.

Ten přesun vytváření stage tabulky a asserty jsou drobnost.

A když mi vysvětlíš ještě ten copy import a pak full import, tak to bude asi OK.

2025-01-17 13:24 UTC, vojtabiberle commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +        );
To vytváření staging tabulky bych přesunul do `if ($isColumnNameIdentical) {` k `CopyImportFromTableToTable`

2025-01-17 13:24 UTC, vojtabiberle commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +            $importResult = $toFinalTableImporter->importToTable(
Úplně nevím, jak tohle má fungovat.

Ale přijde mi to divné. Nejdřív importuješ pomocí `toStageImporter` který je potencionálně `CopyImportFromTableToTable` takže tam už data naleje.

Ale pak ještě nalejváš data přes `FullImporter`

Bohužel tady nemám dostatečnou znalost BQ …

2025-01-17 13:24 UTC, vojtabiberle commented on src/Handler/Table/Import/ImportTableFromTableLib/CopyImportFromTableToTable.php
> +        ));
Raději bych tu viděl vyjímky než asserty, na vyjímky se dá reagovat.

2025-01-17 15:05 UTC, zajca commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +            $importResult = $toFinalTableImporter->importToTable(
Stage importer importuje do dočasné stage tabulky, Full nebo Incremental pak importuje ze stage tabulky do final tabulky.

2025-01-17 15:06 UTC, vojtabiberle commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +            $importResult = $toFinalTableImporter->importToTable(
OK, v tom případě to vypadá dobře :-)

2025-01-17 15:06 UTC, vojtabiberle approved these changes

2025-01-17 15:12 UTC, zajca commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +        );
Chvilku sem nad tím přemýšlal a změnil sem to, dělala sa tam ta stage tabulka 2x stejně

2025-02-17 09:34 UTC, zajca commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +        }
Tady to je upravená důležitá část. Porovnávám stage protože ta sa dělá z destination bez _timestamp sloupce. Abych mohl použit COPY importer potřebuju mět ty tabulky stejné jinak tam padá cast v BQ, takže sem použil assertSameColumns, který tady to dělá.

Prakticky E2E to pokrývá case kdy je tabulka ve WS s typama a tabulka ve Storage bez typů. Tehdy sa vysere ten cast. Pořád je to validní usecase pro platformu, každopádně už není až tak důležitý protože runner by měl zakládat tabulky z WS s typama podle native-types, takže by tady ten assert neměl padat.

2025-02-17 09:36 UTC, zajca commented
@vojtabiberle ještě pro pořádek sem udělal jednu iteraci a opravil case na který sem narazil v E2E testoch kdy sa testuje load z WS kdy je ve WS tabulka s typama a ve storage ne. Tam nešel použit ten COPY protože ta stage tabulka, kterů vytvoří pak nesedí se storage a padá to.

2025-02-17 09:48 UTC, vojtabiberle commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +        }
Jo vypadá to cajk a dává to smysl.

2025-02-17 09:48 UTC, vojtabiberle approved these changes

2025-02-17 18:39 UTC, merged