Big 51 roman import from ws
keboola/php-storage-driver-bigquery pull request #20
Opened 2022-11-23 14:00 UTC by romanbracinik

Big 51

2022-11-25 06:54 UTC, romanbracinik commented on composer.json
> +        "keboola/table-backend-utils": "dev-big-51-roman-import-from-ws as 1.9",
potom zmenim ked tagnem novu verziu

2022-11-25 06:55 UTC, romanbracinik commented on src/Handler/Info/ObjectInfoHandler.php
> +                return $this->getDatabaseResponse($path, $bqClient, $response);
V BQ je projekt ako databaza, 
- vzdy existuje
- nemoze mat nejake dalsie pod projekty
- obsahuje len datasety, tabulky a views

2022-11-25 06:56 UTC, romanbracinik commented on src/Handler/Info/ObjectInfoHandler.php
> +        }
tu oproti TR chyba `yield from $this->getChildSchemas($db, $databaseName);` pretoze nema nejake dalsie child

2022-11-25 06:57 UTC, romanbracinik commented on tests/functional/UseCase/Info/ObjectInfoErrorTest.php
> +    public function testInfoSchemaNotExists(): void
tu netestujem eze existuje databaza (Projekt) pretoze ten existuje vzdy

2022-11-28 08:42 UTC, zajca requested changes
Vypadá to cajk.

2022-11-28 08:42 UTC, zajca commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +    private function createStateTable(
`createStageTable`

2022-11-28 08:42 UTC, zajca commented on src/Handler/Table/Import/ImportTableFromTableHandler.php
> +                // @todo maybe set primary keys if source table has them
Tady to pro BQ neplatí ta PK nemá.
```suggestion
                [] //<-- there are no PK in BQ
```

2022-11-28 08:53 UTC, zajca approved these changes

2022-11-28 09:35 UTC, merged