Roman alter table
keboola/php-storage-driver-bigquery pull request #27
Opened 2022-12-17 16:10 UTC by romanbracinik

[BIG-36](https://keboola.atlassian.net/browse/BIG-36)

2022-12-19 14:47 UTC, jirkasemmler requested changes
jen ty nazvy, mam spatne i u sebe

2022-12-19 14:47 UTC, jirkasemmler commented on src/Handler/Table/Alter/DropColumnHandler.php
> +        assert($command->getColumnName() !== '', 'DropColumnCommand.name is required');
```suggestion
        assert($command->getColumnName() !== '', 'DropColumnCommand.columnName is required');
```

2022-12-19 14:47 UTC, jirkasemmler commented on src/Handler/Table/Alter/DropColumnHandler.php
> +        assert($command->getPath()->count() === 1, 'TableColumnShared.path is required and size must equal 1');
```suggestion
        assert($command->getPath()->count() === 1, 'DropColumnCommand.path is required and size must equal 1');
```

2022-12-19 14:47 UTC, jirkasemmler commented on src/Handler/Table/Alter/DropColumnHandler.php
> +        assert($command->getTableName() !== '', 'TableColumnShared.tableName is required');
```suggestion
        assert($command->getTableName() !== '', 'DropColumnCommand.tableName is required');
```

2022-12-19 14:47 UTC, jirkasemmler commented on src/Handler/Table/Alter/AddColumnHandler.php
> +        assert($command->getTableName() !== '', 'TableColumnShared.tableName is required');
```suggestion
        assert($command->getTableName() !== '', 'AddColumnCommand.tableName is required');
```

2022-12-19 14:47 UTC, jirkasemmler commented on src/Handler/Table/Alter/AddColumnHandler.php
> +        assert($command->getPath()->count() === 1, 'TableColumnShared.path is required and size must equal 1');
```suggestion
        assert($command->getPath()->count() === 1, 'AddColumnCommand.path is required and size must equal 1');
```

2022-12-19 17:36 UTC, romanbracinik commented
Dik upravil som

2022-12-21 08:08 UTC, jirkasemmler approved these changes
cool!

2022-12-21 08:39 UTC, merged