Fix return datetime in table preview
keboola/php-storage-driver-bigquery pull request #44
Opened 2023-04-23 18:08 UTC by romanbracinik

2023-04-24 12:09 UTC, tomasfejfar requested changes

2023-04-24 12:09 UTC, tomasfejfar commented on tests/functional/UseCase/Table/PreviewTableTest.php
> +                    "3, 200, 200.23, '200.23', 200.23456, '2022-01-02', '12:00:10', '2022-01-01 12:00:10', '%s', '1989-08-31 02:00:00'",
```suggestion
                        "3, 200, 200.23, '200.23', 200.23456, '2022-01-02', '12:00:10', '2022-01-01 12:00:10', '%s', '1989-08-31 02:00:00'",
```

2023-04-24 12:09 UTC, tomasfejfar commented on src/Handler/Table/Preview/PreviewTableHandler.php
> +                        $columnValue = $columnValue->format('Y-m-d H:i:s');
Neměla by tady být nějak zohledněná timezone nebo není v té response?

2023-04-24 12:09 UTC, tomasfejfar commented on src/Handler/Table/Preview/PreviewTableHandler.php
> +                        $columnValue = $columnValue->format('Y-m-d H:i:s');
Třeba tady \Keboola\Db\ImportExport\Backend\Snowflake\Helper\DateTimeHelper::getNowFormatted řešíme, aby to co se vrátí z formátu bylo v UTC.

Ale možná je to očekávané - že to z commandu přijde bez TZ

2023-04-24 13:34 UTC, tomasfejfar commented
TIL: PhpStorm "chytře" formátuje .env file zalamováním řádků 🤦

2023-04-25 05:38 UTC, romanbracinik commented on src/Handler/Table/Preview/PreviewTableHandler.php
> +                        $columnValue = $columnValue->format('Y-m-d H:i:s');
Hm pozeral som tu reprezentaciu Datetime v BQ a https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#datetime_type  
```
A datetime value represents a date and time, as they might be displayed on a watch, independent of time zone. It includes the year, month, day, hour, minute, second, and subsecond. To represent an absolute point in time, use a [timestamp](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type).
```

2023-04-25 10:28 UTC, tomasfejfar approved these changes
Rovnou jsem to upravil

2023-04-25 10:28 UTC, tomasfejfar commented on tests/functional/UseCase/Table/PreviewTableTest.php
> +                    "2, 100, 100.23, '100.20', 100.23456, '2022-01-01', '12:00:10', '2022-01-01 12:00:10', 'Variable 2', '1989-08-31 01:00:00'",
```suggestion
                    "2, 100, 100.23, '100.20', 100.23456, '2022-01-01', '12:00:10', '2022-01-01 12:00:10', 'Variable 2', '1989-08-31 01:00:00.123'",
```

2023-04-25 10:28 UTC, tomasfejfar commented on tests/functional/UseCase/Table/PreviewTableTest.php
> +                    "2, 100, 100.23, '100.20', 100.23456, '2022-01-01', '12:00:10', '2022-01-01 12:00:10', 'Variable 2', '1989-08-31 01:00:00'",
Chybí test, který by testoval to, jestli to správně zparsuje a převede ty microsekundy

2023-04-27 11:30 UTC, merged