Big 126 external buckets
keboola/php-storage-driver-bigquery pull request #48
Opened 2023-05-27 12:55 UTC by romanbracinik

2023-05-29 07:04 UTC, romanbracinik commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +            $command->getProjectReadOnlyRoleName() !== '',
Toto este hodim  do nejake variable, v kontxtu BQ sa jedna o nazov datasetu (bucektu)

2023-05-29 07:06 UTC, romanbracinik commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +            $command->getBucketObjectName() !== '',
$command->getProjectReadOnlyRoleName(), $command->getBucketObjectName() mozno este prehodim v kontextu bq to obsahuje ine veci ako sa teraz aktualne poosielaju z connection.

getProjectReadOnlyRoleName - sa pouziva pre  meno datasetu (bucketu)
getBucketObjectName - sa pouziva pre listing vytvoreneho pre externy bucket, a posle sa v parametre pri registacii.

2023-06-02 15:04 UTC, jirkasemmler commented
> Najskor sa tam vy tiahnu tabulky, potom sa zavola commnad. V BQ ale tabulky v tom externom buckete ziskam az ked zavolam ten commnad, pretoze v podstate registracia bucketu je linknutie toho datasetu do cieloveho projektu.

koukam na to a nemel by to byt problem

2023-06-02 16:18 UTC, jirkasemmler requested changes, later dismissed
myslim, ze musime domyslet predavani toho bucketu a role a pak nejak asi spolecne to dokuchtit v connection

2023-06-02 16:18 UTC, jirkasemmler commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +            $command->getBucketObjectName() !== '',
nevim jestli bych to presouval, spis otocil ne? 
ten listing (a jeho navazna subscription) vlastne imituje RO roli. a ten objectName je bucket (dataset), ktery chci sdilet. 

pokud to chapu takto spravne, tak si dovedu predstavit (s dostatecnym komentarem), ze to tak nechame. misto toho to davat do meta

2023-06-02 16:18 UTC, jirkasemmler commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +                throw new Exception(
myslim, ze bychom na to meli implementovat vlastni exception, zejmena imho by mela byt `NonRetryableExceptionInterface`

2023-09-01 10:11 UTC, romanbracinik commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +            $command->getBucketObjectName() !== '',
Jj tak som to myslel,

$command->getProjectReadOnlyRoleName() = listing
$command->getBucketObjectName() = meno linknuteho bucketu v cielovom projekte

2023-09-01 10:12 UTC, romanbracinik commented on src/Handler/Bucket/Drop/RevokeBucketAccessFromReadOnlyRoleHandler.php
> +        assert($command instanceof RevokeBucketAccessFromReadOnlyRoleCommand);
Tu som vlastne zbytocne pridaval branchId do commonu v dalsom PR to zmazem, je to rovnake ako delete bucket v podstate, ale nechal som to ako zvlast handler nech dodrzujem "interface"

2023-09-01 10:13 UTC, romanbracinik commented on src/Handler/Table/ObjectAlreadyExistsException.php
> +                message: 'Object already exists.',
Len fix toho co tam bolo :)

2023-09-04 12:28 UTC, tomasfejfar commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +        // This is the name of a bucket created in the target project that represents an external bucket
Takže je to jen pro ext bucket? Jak se to dělá pro jiné buckety?

2023-09-04 12:28 UTC, tomasfejfar commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +        }
Proč je tohle potřeba jen tady a jinde ne? A proč vůbec podporujeme variantu, kde $stackPrefix není nastavený?

2023-09-04 12:28 UTC, tomasfejfar commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +        }
A druhá věc ještě - myslel bych si, že se to nemá tahat takhle na prasáka z ENVu uprostřed kódu, ale mělo by to dostat v konstruktoru.

2023-09-04 12:28 UTC, tomasfejfar commented on src/Handler/Bucket/Drop/RevokeBucketAccessFromReadOnlyRoleHandler.php
> +        $dataset->delete();
Nemělo by tu být odsazení?! :)

2023-09-04 12:28 UTC, tomasfejfar commented on src/Handler/Bucket/Drop/RevokeBucketAccessFromReadOnlyRoleHandler.php
> +        $dataset->delete();
S tím listingem není potřeba tím pádem nic dalšího dělat? Resp. je to na uživateli, aby odebral tomu projektu práva.

2023-09-04 12:28 UTC, tomasfejfar commented on tests/functional/UseCase/Bucket/GrantRevokeBucketAccessToReadOnlyRoleTest.php
> +        $handler = new GrantBucketAccessToReadOnlyRoleHandler($this->clientManager);
Je to potřeba? Už je na ř.72

2023-09-04 12:28 UTC, tomasfejfar commented on tests/functional/UseCase/Bucket/GrantRevokeBucketAccessToReadOnlyRoleTest.php
> +        $handler = new GrantBucketAccessToReadOnlyRoleHandler($this->clientManager);
Akorát by asi kvuli phpstnau musel být venku z try/catch

2023-09-04 12:28 UTC, tomasfejfar commented on tests/functional/UseCase/Bucket/GrantRevokeBucketAccessToReadOnlyRoleTest.php
> +        $command = (new GrantBucketAccessToReadOnlyRoleCommand())
Ten command by taky být nemusel 2x, imho

2023-09-04 12:28 UTC, tomasfejfar commented on tests/functional/UseCase/Bucket/GrantRevokeBucketAccessToReadOnlyRoleTest.php
> +        $command = (new GrantBucketAccessToReadOnlyRoleCommand())
Naopak by bylo jasné, že jakmile to grantneš, tak ten samý command projde

2023-09-04 18:23 UTC, romanbracinik commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +        }
https://github.com/keboola/storage-backend/pull/83 este budu teraz testy failovat pretoze nieje mergnuty common

2023-09-05 11:36 UTC, romanbracinik commented on src/Handler/Bucket/Create/GrantBucketAccessToReadOnlyRoleHandler.php
> +        // This is the name of a bucket created in the target project that represents an external bucket
Vyriesene na calle

2023-09-05 11:37 UTC, romanbracinik commented on src/Handler/Bucket/Drop/RevokeBucketAccessFromReadOnlyRoleHandler.php
> +        $dataset->delete();
vyriesene na calle, listing sa zmaze (odlinkuje) z cieloveho projektu to co sa potom stane s externym datasetom je na majtelovy tak ako je to v pripade inych backendov

2023-09-05 11:38 UTC, romanbracinik commented
common driver je upratnuty, moze to ist na review este som otocil build nech to prebehne ale lokalne to fici

2023-09-05 11:49 UTC, tomasfejfar approved these changes
LGTM

2023-09-05 12:52 UTC, merged