GCP-367 Wait for permissions
keboola/php-storage-driver-bigquery pull request #76
Opened 2023-10-13 13:02 UTC by jirkasemmler

2023-10-16 07:43 UTC, zajca requested changes
Ta hláška je docela na prd. Takže bych ju změnil. Bohužel tam je jiný problém, že ten SA prostě ty role nedostane to vypadá, nebo je ten retry moc krátký.
pustil sem to v paratestu (takto sa pustí úplně všecko):
```
dc run --rm dev composer paratest
```

A stejně to padá :/

2023-10-16 07:43 UTC, zajca commented on src/Handler/Workspace/Create/CreateWorkspaceHandler.php
> +            );
Ta hláška je na prd docela, představsi, že to na tebe vyskočí v ops-erros.

```suggestion
            if ($expected !== $serviceAccRoles) {
                throw new RuntimeException(sprintf(
                    'Workspace service account has incorrect roles. Expected roles: [%s], actual roles: [%s]',
                    implode(',', $expected),
                    implode(',', $serviceAccRoles)
                ));
            }
```

2023-10-16 07:45 UTC, jirkasemmler commented
@zajca tak zkusim poladit delsi backoff. je tam ten defaultni z retry libky

2023-10-16 08:07 UTC, zajca commented
> @zajca tak zkusim poladit delsi backoff. je tam ten defaultni z retry libky

Co sem tak zkůšal tak to vypadá, že ani svědcená voda nepomože, ne tak víc retry :D Dal sem tam místo 5ti pokusí dvacet a stejně to občas spadne. 
Přemýšlám jestli to pak třeba nepokryje retry kdy sa ti pustí znova storage job. Ale nedokážu vyhodnotit jestli ten retry nějak pomáhá nebo ne.

2023-10-16 14:28 UTC, jirkasemmler commented
@zajca neni resenim spis zvednout delay nez pocet retry? zkusil jsem https://github.com/keboola/php-storage-driver-bigquery/pull/76/commits/ed6ea0134dcd0cc049331fca43ab113cac97e82c a toto v testech proslo. ono totiz `ExponentialBackOffPolicy` ma default delay 100ms a myslim, ze to bude na BQ moc zhurta

2023-10-17 07:56 UTC, zajca commented
Udělal sem rebase a přidal ještě nějaké retry na které sem narazil. Ale aj tak sa mě teda stává, že když to pustím v paratestu 16threadů tak to spadne :/

2023-10-17 09:06 UTC, zajca commented
Ještě sem to upravil. obalil sem ten retry do dalšího retry včetně setIam a funguje to. Nespadlo mě to lokálně ani jednů.

2023-10-17 10:40 UTC, zajca approved these changes
Takto by to podle mě šlo, je to backoff in backoff in backoff, ale funguje to a nepadá :D

2023-10-17 10:52 UTC, merged